require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.1

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude: 
    - 'db/*.rb'
    - 'db/**/*.rb'
    
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/environments/*.rb'
    - 'config/initializers/*.rb'

Layout/LineLength:
  Exclude: 
    - 'config/initializers/*.rb'

Rails/BulkChangeTable: 
  Exclude:
    - 'db/migrate/*.rb'

Lint/AmbiguousBlockAssociation:
  IgnoredMethods: [change]

Style/ClassVars:
  Exclude:
    - 'spec/rails_helper.rb'
