default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: Rails.application.credentials[:db_username],
  password: Rails.application.credentials[:db_password],

development:
  <<: *default
  database: rg_booktore_development

test:
  <<: *default
  database: rg_booktore_test

production:
  <<: *default
  database: rg_booktore_production
